### ISSUE TITLE
ArrayIterator: ValueOutOfRangeException on emptry array.

### ISSUE THREAD

**Issue by hohwille** [m-m-m/util#158]
If ArrayIterator is created for an empty array an ValueOutOfRangeException is thrown:
```
net.sf.mmm.util.value.api.ValueOutOfRangeException: ValueOutOfRange: The value 0 from "start" needs to be in the range from 0 to -1.
90bafd06-c412-49d0-b35d-7f2c0d50e157
	at net.sf.mmm.util.value.api.ValueOutOfRangeException.checkRange(ValueOutOfRangeException.java:155)
	at net.sf.mmm.util.collection.base.ArrayIterator.<init>(ArrayIterator.java:66)
	at net.sf.mmm.util.collection.base.ArrayIterator.<init>(ArrayIterator.java:39)
```

**Comment by hohwille** [comment]
OMG. Really stupid bug that I will fix asap.

**Comment by hohwille** [comment]
Done.
