### ISSUE TITLE
Travis fails: ProcessUtilSpringTest>ProcessUtilTest.testExecuteAsyncStop:108 null

### ISSUE THREAD

**Issue by hohwille** [m-m-m/util#165]
Since build 87 travis always reports this test failure:

```
Tests run: 6, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.36 sec <<< FAILURE! - in net.sf.mmm.util.process.base.ProcessUtilSpringTest

testExecuteAsyncStop(net.sf.mmm.util.process.base.ProcessUtilSpringTest)  Time elapsed: 0.013 sec  <<< FAILURE!

java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at net.sf.mmm.util.process.base.ProcessUtilTest.testExecuteAsyncStop(ProcessUtilTest.java:108)
```

**Comment by hohwille** [comment]
I assume that java changed on path in travis for docker container recently for some reason.
The only chance seems to put such fragile tests on ignore.

**Comment by hohwille** [comment]
Travis now passing.
