### ISSUE TITLE
java.lang.NullPointerException: repository cannot be null

### ISSUE THREAD

**Issue by hohwille** [m-m-m/util#5]
When the search-indexer is working incremental using "vcs" as strategy (and "svn" as type) I get this exception:

An unexpected error has occurred:
java.lang.NullPointerException: repository cannot be null

    at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:49)
    at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.executeCommand(AbstractSvnScmProvider.java:356)
    at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.info(AbstractSvnScmProvider.java:377)
    at org.apache.maven.scm.provider.svn.svnexe.SvnExeScmProvider.getRepositoryURL(SvnExeScmProvider.java:150)
    at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.makeProviderScmRepository(AbstractSvnScmProvider.java:119)
    at org.apache.maven.scm.manager.AbstractScmManager.makeProviderScmRepository(AbstractScmManager.java:267)
    at net.sf.mmm.search.indexer.impl.strategy.SearchIndexerUpdateStrategyVcs.index(SearchIndexerUpdateStrategyVcs.java:201)

**Comment by hohwille** [comment]
mmm-search has been moved to separate repository.
